### ISSUE TITLE
Create Starter Child Theme for LSX Design and Publish as Minimal LSX Theme on WordPress.org

### ISSUE THREAD

**Issue by ashleyshaw** [lightspeedwp/lsx-design#178]
### Description
Develop a starter child theme for LSX Design and publish it as the Minimal LSX theme on WordPress.org. This process includes creating an asset for GitHub release and following best practices as outlined in the OllieWP repository.

### Tasks
- [ ] Create the starter child theme based on LSX Design.
- [ ] Prepare the child theme asset for GitHub release.
- [ ] Follow the example from OllieWP: [OllieWP Release](https://github.com/OllieWP/ollie/releases/tag/1.1.0).
- [ ] Publish the child theme to the Minimal LSX theme on WordPress.org
- [ ] update the templates and styles to be more minimal.
- [ ] updated wp.org description & screenshot

### Links
- Dev site - https://minimal.lsx.design/
- Create a minimal child theme > publish as an LSXD child
- https://minimal.lsx.design/wp-admin/themes.php?page=create-block-theme
- https://wordpress.org/themes/minimal-lsx/
- https://github.com/lightspeedwp/minimal-lsx-child.

### Acceptance Criteria
- [ ] The starter child theme is developed and tested for compatibility.
- [ ] The theme asset is properly packaged and released on GitHub.
- [ ] The Minimal LSX theme is successfully published on WordPress.org.
