### ISSUE TITLE
WooCommerce Memberships - Compatibility

### ISSUE THREAD

**Issue by krugazul** [lightspeedwp/lsx-design#30]
### **Description**
We need to look at the various screens that the WC Memberships plugin creates, and make sure we have templates, patterns or styling to handle the layouts.

You can use the LightSpeed user to view the following screens.  It has been setup with a Platinum Plan expiring in 2025.

### **Tasks**

- [ ] [Membership plans](https://demo.lsx.design/membership-plans/) - Not a template, requires a pattern.
- [ ] [Single Membership](https://demo.lsx.design/product/platinum-membership/)
- [ ] [Restricted Post](https://demo.lsx.design/memberships-restricted-post/)
- [ ] [My Account - My Memberships](https://demo.lsx.design/my-account/members-area/) (members area, visible when you have more than 1 plan)
- [ ] [My Account - My Membership Content](https://demo.lsx.design/my-account/members-area/2026/my-membership-content/)

#### [Membership plans](https://demo.lsx.design/membership-plans/)
![screencapture-demo-lsx-design-membership-plans-2023-08-02-08_48_04](https://github.com/lightspeedwp/lsx-design/assets/1805603/0f6bc634-b836-4efe-9211-f0e486708be1)

#### [Single Membership](https://demo.lsx.design/product/platinum-membership/)
![screencapture-demo-lsx-design-product-platinum-membership-2023-08-02-08_52_45](https://github.com/lightspeedwp/lsx-design/assets/1805603/eb024fe8-b73a-4ea5-954e-8be05b28f068)

#### [My Account - My Memberships](https://demo.lsx.design/my-account/members-area/)
![screencapture-demo-lsx-design-my-account-members-area-2023-08-02-08_06_46](https://github.com/lightspeedwp/lsx-design/assets/1805603/87a162bc-eac7-47d8-9821-0d91f4354b44)

#### [My Account - My Membership Content](https://demo.lsx.design/my-account/members-area/2026/my-membership-content/)
![screencapture-demo-lsx-design-my-account-members-area-2026-my-membership-content-2023-08-02-08_38_45](https://github.com/lightspeedwp/lsx-design/assets/1805603/624283d2-c379-46cc-83fc-65b83829cbb2)

#### [Restricted Post](https://demo.lsx.design/memberships-restricted-post/)
![screencapture-demo-lsx-design-memberships-restricted-post-2023-08-02-08_53_16](https://github.com/lightspeedwp/lsx-design/assets/1805603/23370c33-551d-463e-b540-54b6c3cd293e)
