### ISSUE TITLE
Patterns have colour &amp; spacing issues

### ISSUE THREAD

**Issue by ashleyshaw** [lightspeedwp/lsx-design#34]
**Describe the bug**
Version 1.0 of LSX Design theme has various issues with theme patterns, these issues needed to be addressed by improving designs so that a clear 

**To Reproduce**
1. Go to the Site Editor
2. Click on 'Patterns'
3. Review each pattern carefully against the designs & address any spacing, colour or other discrepancies.

**Tasks**

- [x] Colour Issues
- [x] Spacing issues causing block errors
- [ ] All patterns need to be compared to the designs
- [ ] All page templates need to be compared to the designs
- [ ] All template parts need to be compared to the designs

**Designs**
Patterns - https://www.figma.com/file/U3MB5DRLxHpQDoDs2Pi2jG/LSX-WordPress?type=design&node-id=1151-16&mode=design&t=PGkRDb5NlGP94mNq-0

Full Page Patterns - https://www.figma.com/file/U3MB5DRLxHpQDoDs2Pi2jG/LSX-WordPress?type=design&node-id=1151%3A17&mode=design&t=7yWXAmGZJXuF4WtX-1

**Comment by krugazul** [comment]
@ashleyshaw and @Justinabes007,  I have fixed the colour issues on all of the patterns.  The quaternary colour was being used.  I have set that to the base colour.  That makes it work with the style switcher as well.

I have fixed some of the spacing issues causing the "invalid block" issues.  These will be included in 1.1.0,  but the rest of the spacing issues will need to be reviewed in 1.1.1
