### ISSUE TITLE
WP 6.4 - Lightbox is active on all images

### ISSUE THREAD

**Issue by krugazul** [lightspeedwp/lsx-design#57]
**Description**
The new WP6.4 lightbox adds the tags to all images that output.  So all images are combined into 1 gallery on a page.

**To Reproduce**
With the new WP 6.4 installed, load a few galleries onto a page, and click one of the images.  You will see all of them are in 1 gallery.

**Expected behaviour**
We would like to specifically enable it for certain images, such as only the WP gallery on a page, and not have the featured image included in that.

**Tasks**
- [ ] Add in a "close" button to the modal. (might be a setting)
- [ ] Research how the rel tags are being added, and what filters are being used.
- [ ] Restrict the lightbox to the WP gallery block.

**Screenshots**
<img width="1096" alt="Screenshot 2023-11-13 at 09 56 05" src="https://github.com/lightspeedwp/lsx-design/assets/1805603/1c4a8687-c49f-4626-9e24-28bca56b4b1e">
